### ISSUE TITLE
Write the base importer

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#101]
**ACCEPTANCE**
When I supply a minimal valid CSV and upload the associated files to my SFTP folder.
- [x] A new work is created for each row in the CSV with the specified file attached
- [x] Add content to a collection as directed
- [x] It should attach files from `/opt/data/client/uploads` even if they are in a subdirectory

**Comment by bess** [comment]
![import_working.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e1998a2c90979698e6ad48ad53f7d665043761260ea62864c7b96aea402a585b5648ad41510943aefe892ba7e53c228c0e59ebc3714d36976345f3e5db55ea43a82a994e8dbcbd8f48c8e13b26e782874e3c1f1755.png)

**Comment by bess** [comment]
You can try this by submitting this CSV file: https://raw.githubusercontent.com/curationexperts/tenejo/master/spec/fixtures/csv_import/modular_input.csv

The files it references have already been uploaded on tenejo-cd and tenejo-dev

**Comment by mark-dce** [comment]
I'm also able to import new works -

I used this CSV 
https://gist.github.com/mark-dce/9c11624399c3983cac2c9dd867560b28#file-loc-images-csv

To create the works in this collection https://tenejo-cd.curationexperts.com/collections/wm117n96b?locale=en

![101 - test collection](https://user-images.githubusercontent.com/3064318/52243242-afbf3b80-289e-11e9-8d01-a1ab2fe665a5.png)
