### ISSUE TITLE
Download CSV template instead of displaying in browser

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#110]
**ISSUE**
When I click on the "Download CSV Template" link from the dashboard, the text displays in my browser instead of downloading as a .csv file.

**ACCEPTANCE**
- [x] When I click on the "Download CSV template", `import_manifest.csv` downloads to my local system instead of displaying in my browser.

**Comment by val99erie** [comment]
Suggestion:  We should configure Rails to allow Apache (or whatever is the server in prod) to serve files from the public directory (instead of Rails).

**Comment by mark-dce** [comment]
@mark-dce will do more testing and figure out if this is a Safari specific issue.

**Comment by mark-dce** [comment]
The problem is specific to Safari; I get the desired behavior in Chrome.  I updated the problem description accordingly.

**Comment by mark-dce** [comment]
I'm guessing we need to provide appropriate header fields to force Safari to behave in the same way as chrome, so we'd need to do something beyond serving the file from `/public` that would allow us to provide  the following HTTP headers:
* `Content-Disposition: attachment; filename="import_manifest.csv"`
*`Type: xapplication/octet-stream`

**Comment by mark-dce** [comment]
Works great, Safari is downloading the file to my downloads folder now (just like Chrome always did).
