### ISSUE TITLE
Visibility values in the CSV should match the Edit UI

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#115]
**STORY**
As a new tenejo client, I want to be able to use the same visibility terms in batch uploads as I see in the UI, so that I don't have to learn two sets of terms for the same thing.

**DETAILS:* In the UI, visibility is listed as `Public`, `DCE`, and `Private`; in the importer, it sounds like we need to use `open`, `registered`, and `restricted`

**ACCEPTANCE**
- [x] the visibility field for an import accepts the labels that show up in the UI 
- [x] In addition to the institution name for restricted works, I can also use the word `Authenticated` (so we can write generic documentation)
- [x] visibility values are not case sensitive - i.e. `public`, `Public`, and `pUBLIc` are all valid and mean the same thing
- [x] if the visibility does not match an expected value the system should import the work as `restricted`

**Comment by mark-dce** [comment]
Using a set of works with the following visibility settings:

resource type | visibility 
------------------|------------
Image | pRiVaTe
Image | public
Image | Private	
Image | PUBLIC
Image | Authenticated
Image | open

I'm  getting the following error in sidekiq  
`ArgumentError: Invalid visibility: "registered"`

<img width="1183" alt="115 - visibilty error" src="https://user-images.githubusercontent.com/3064318/52618234-dadbf900-2e63-11e9-9094-02eba506f476.png">

**Comment by bess** [comment]
New PR fixing this bug submitted to Darlingtonia: https://github.com/curationexperts/darlingtonia/pull/63

**Comment by mark-dce** [comment]
With the following visibilities, I get the expected results below

with the following visibilities

visibility

ResTricted
Private
PUBLIC
Authenticated
open

![115 - visibility import fixed](https://user-images.githubusercontent.com/3064318/52660440-499d6e80-2ec5-11e9-88b9-ec748944ebb5.png)
