### ISSUE TITLE
A CSV with missing required values should trigger a warning

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#116]
**STORY**
As a user submitting content, I'd like the system to report all the detectable warnings in my CSV file, so that I don't have to repeatedly fix one issue only to have the next one reported.

*NOTE:* for the first pass, we can treat both an empty cell `,,` and a cell with an empty string `,'',` as being a missing value.

Child of #95 

**ACCEPTANCE**
Given a sample file  like `missing-values.csv` or `multiple-missing-values.csv` below 
- [x] I should get a warning message
- [x] The message should indicate the row number and field (header) name for each missing required value;  If multiple values are missing for a line,
    - [x] All the missing values should be reported for each line
- [x] The message should say something like "Line 3: the field 'visibility` is missing a required value"

**missing-values.csv**  
(*note: in this sample each line is missing one required value*)

title | creator | keyword | rights_statement | visibility | files
-- | -- | -- | -- | -- | --
In March read the books you've always meant to read | unknown | Books\|~\|Color\|~\|Illinois\|~\|Libraries\|~\|Posters\|~\|Reading\|~\|Screen Prints | No known restrictions on publication. | open |  
Keeping up with science / Shari | Weisberg, Shari | Color\|~\|Education\|~\|Microscopes\|~\|Posters\|~\|Science\|~\|Screen Prints | No known restrictions on publication. |   | 3b48702u.tif
The national parks preserve wild life | unknown | Color\|~\|Mountain Sheep\|~\|National Park Service\|~\|National Parks & Reserves\|~\|Public Relations\|~\|Screen Prints\|~\|Tourism\|~\|Travel Posters\|~\|United States |   | open | 23061u.tif
See America Welcome to Montana / / R. Halls | Halls, Richard, 1906- |   | No known restrictions on publication. | open | 3b48734u.tif
See America / Frank S. Nicholson |   | Color\|~\|Cowboys\|~\|Rock Formations\|~\|Screen Prints\|~\|Tourism\|~\|Travel Posters | No known restrictions on publication. | open | 3b48731u.tif
  | Halls, Richard, 1906- | Art Exhibitions\|~\|Color\|~\|Exhibition Posters\|~\|New York (State)\|~\|Printmaking\|~\|Screen Prints | No known restrictions on publication. | open | 3f05512u.tif

`multiple-missing-values.csv`
(*note: in this sample lines 3 through 6 are missing more than one value*)

title | creator | keyword | rights_statement | visibility | files
-- | -- | -- | -- | -- | --
In March read the books you've always meant to read | unknown | Books\|~\|Color\|~\|Illinois\|~\|Libraries\|~\|Posters\|~\|Reading\|~\|Screen Prints | No known restrictions on publication. | open | 3f05175u.tif
  | Weisberg, Shari |   | No known restrictions on publication. | open | 3b48702u.tif
The national parks preserve wild life |   | Color\|~\|Mountain Sheep\|~\|National Park Service\|~\|National Parks & Reserves\|~\|Public Relations\|~\|Screen Prints\|~\|Tourism\|~\|Travel Posters\|~\|United States |   | open | 23061u.tif
See America Welcome to Montana / / R. Halls | Halls, Richard, 1906- |   | No known restrictions on publication. |   | 3b48734u.tif
  | Nicholson, Frank S. |   | No known restrictions on publication. |   | 3b48731u.tif
Prints for the people A national exhibition of prints made by artists employed by the Federal Art Project of the Works Progress Administration |   | Art Exhibitions\|~\|Color\|~\|Exhibition Posters\|~\|New York (State)\|~\|Printmaking\|~\|Screen Prints |   | open |

**Comment by val99erie** [comment]
@mark-dce Can you confirm that these should be warnings (can continue import) and not errors (import will be aborted)?

For the case of the "Title" field, it must be an error, but for all the other fields, we can go ahead and import with blank metadata.

**Comment by mark-dce** [comment]
In our design sessions, we said that warnings meant don't import rows with one or more errors, but import any rows that have no errors.  So if I have a CSV with 6 data rows and only one has a warning, we should import 5 things and not attempt to import the row that triggered the warning at all.

**Comment by val99erie** [comment]
@mark-dce The importer currently doesn't have that fuctionality.  Right now our options are to let the full import go ahead or not.  We could add that functionality, but that would be much more work, and we'd probably need 4 or 5 separate stories for it.

**Comment by val99erie** [comment]
@mark-dce Actually, it might not need separate stories.  I had a particular implementation in mind when I said that.  It's probably best to have just one story that describes which fields being blank would cause importer to skip importing that record.

I do remember us discussing that at design meeting, but as far as I know, we never wrote a story for it.

**Comment by mark-dce** [comment]
For now, let's treat them as hard-stop errors.  Is there a way, thought, to keep reporting them as warnings and for now, have any import with warnings or errors prevent us from importing - i.e. we should warnings and errors separately like currently happens, but make the user "Try Again" any time there are either warnings or errors?

**Comment by val99erie** [comment]
I don't like the idea of mixing the functionality of warnings vs errors.  This is the current behavior, which I would like to keep:

* "errors" means show-stopper errors.  You cannot proceed with the import.

* "warnings" means user needs to review warnings and decide whether or not to continue the import.  (and future behavior: some warnings might cause the importer to skip that particular record)

Reasons I want to avoid blurring the boundaries between error and warnings:

* Follows Rails conventions that you can't submit a form when you have errors.  (Also, Hyrax has the same convention.)

* It's better UI.  The user might feel uneasy continuing an import if there are "errors".  "Warning" is softer language, and not as scary.

* Easier to code because I don't need to keep track of which errors and warnings are show-stoppers and which ones can be overridden by the user.  Currently there is a clear distinction in how the form behaves for  errors vs warnings.  If we blur those boundaries, the code will become very complicated.

**Comment by val99erie** [comment]
@mark-dce 

I wrote story #206 to implement the code for having the importer skip records that are missing required fields.

For this story, I recommend we just have hard-stop errors for missing values.  Technically, we can import records without some of those fields, but then if the user tries to edit those records in the UI, the edit form will tell the user it's invalid until they fill in the missing fields.  That seems unnecessarily confusing for the poor user.

In the future, when we implement #206, we can change some or all of those errors to warnings to get the final desired behavior.

**Comment by mark-dce** [comment]
👍 Totally agreed, I think there are four classes of issues that we might detect and need to handle separately:

* FILE ERRORS that prevent us from being able to import any record - e.g. missing a required column like `title` for the whole file
* ROW ERRORS that prevent us from importing a specific row because of a missing required value for a field like `title`, `file`, or `rights_statement`
* FILE WARNINGS that suggest the file may have issues but that don't prevent import - e.g. an extra column like `longitude` that we don't recognize
* ROW WARNINGS that suggest the row may have issues but don't prevent us from importing the row with missing data - e.g. an invalid `license` value

Right now for FILE ERRORS we halt the import.  Right now for FILE WARNINGS and ROW WARNINGS we provide the option of allowing the import to proceed.

For now let's halt the import on ROW ERRORS like you suggest.  Then once we've had time to implement #206, we would update the UI to provide an option that says something like "would you like to omit the # rows with errors and proceed with the import of the remaining rows?"

**Comment by mark-dce** [comment]
![image](https://user-images.githubusercontent.com/3064318/53039162-25510d00-3444-11e9-9c5c-f7a28c8cb099.png)
