### ISSUE TITLE
Add splunk to tenejo

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#139]
All our tenejo servers should send their logs to splunk so if we hit a systems problem (e.g., tomcat stopping for no known reason) we can track it down easily.

**Comment by little9** [comment]
You should be able to access the logs for all the tenejo servers now: 

![Screenshot from 2019-02-11 10-12-00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f3793dd4b268ee1236505d424eac53444d04bea6d37ef5f22e7a985959ecd8695672c73d18fabfd018bf01bb738b1d83e4ee8c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cff42e14c50a714306ae6647b.png)

**Comment by mark-dce** [comment]
Yay!!!

<img width="1440" alt="139 - configure splunk" src="https://user-images.githubusercontent.com/3064318/52647651-c2db9800-2eaa-11e9-83f5-cd57c622f6ef.png">
