### ISSUE TITLE
Items not importing to a collection

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#152]
**ISSUES**
Starting this morning, when I import a new csv manifest, the works are no longer being added to the collection I select.

**STEPS TO REPRODUCE**
1. Login as an administrator
1. Start a CSV Import
   1. Use any valid CSV
   1. Select a collection to add to
1. Start your import
1. Wait for background jobs to complete

**EXPECTED REULTS**
My works appear in the collection I selected when I started the import.

**ACTUAL RESULTS**
My works are created (I can see them in all works), but the are not added to any collection.  

*NOTE:* you can verify this by  
1. looking at the collection - you won't see any new members
2. looking at the work - go to all works and find the newly created work, open the single item view and notice that no collections are listed under relationships: 

This work was imported on Friday https://tenejo-cd.curationexperts.com/concern/works/tx31qh68h and has a collection  
<img width="636" alt="150 - imported with collection" src="https://user-images.githubusercontent.com/3064318/52359256-25421d80-29ff-11e9-8b69-6e55d24112f0.png">

This work was imported this morning using the same metadata and does not show any collection membership https://tenejo-cd.curationexperts.com/concern/works/t722h8817  
<img width="612" alt="150 - imported with no collection" src="https://user-images.githubusercontent.com/3064318/52359257-25421d80-29ff-11e9-896f-202abe9a8f59.png">

**Comment by bess** [comment]
I cannot re-create this behavior. I can't figure out how to annotate this screenshot on linux, but see below for a screenshot of a CSV uploaded image that was successfully added to a collection. I have also added collection membership to the checks performed by `spec/system/import_from_csv_spec.rb` and it passes there (PR forthcoming). @mark-dce Can you try this again and see if you're still seeing the same behavior?

![Selection_001.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46db9196268197a080e78013f40cb2d86b56357c2301a03f32dfa17dbd13225556594fac480e5816fbf9892af5b66e76d80e0dffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e45c8e1352de4838a4f380c48.png)

**Comment by mark-dce** [comment]
I can no longer replicate the issue that Rachel and I were seeing last week either.  Thanks for adding the feature test.

![152 - collection import fixed](https://user-images.githubusercontent.com/3064318/52574489-0a4a2180-2de2-11e9-979a-2c529d02c8f4.png)
