### ISSUE TITLE
Importer should set `Date Added`

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#166]
**STORY**
As a tenejo client, I would like the system to track when items were added to the repository regardless of whether I added them via the single item UI or via CSV import.

**ACCEPTANCE**
- [x] Items added via the CSV importer show the date the import was run in the `Date Added` column on the dashboard.

![166 - date added](https://user-images.githubusercontent.com/3064318/52575371-b17b8880-2de3-11e9-8608-585b433a5be2.png)

**Comment by bess** [comment]
To fix this we need to remove `date_uploaded` from the metadata being passed by Darlingtonia. Hyrax expects to set `date_uploaded` itself, and when we pass it in as a metadata field we write over Hyrax's timestamp. PR here: https://github.com/curationexperts/darlingtonia/pull/62

**Comment by mark-dce** [comment]
Looks good - see `Date Added` column in screenshot below

![115 - visibility import fixed](https://user-images.githubusercontent.com/3064318/52660645-c03a6c00-2ec5-11e9-9bb0-661c6bfb5e66.png)
