### ISSUE TITLE
Check for valid rights statements

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#177]
Since submitting an invalid license statement causes an application error, it's a safe bet that submitting an invalid rights statement will do the same thing.

- [x] Check that any rights statement submitted is one of the controlled vocabulary options expected by Hyrax and raise an error if it isn't

**Comment by mark-dce** [comment]
<img width="519" alt="177 - invalid rights statement warning" src="https://user-images.githubusercontent.com/3064318/52974942-fa55b300-3388-11e9-85ab-95c08b6336e5.png">

i.e. CC-Public Domain is a license value, not a valid rights statement
