### ISSUE TITLE
Make a Tenejo Release

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#179]
Depends on curationexperts/darlingtonia#65

**Comment by bess** [comment]
v1.3 released and deployed to:
* https://tenejo-stage.curationexperts.com/
* https://tenejo.curationexperts.com/

**Comment by mark-dce** [comment]
![179 - tenejo 1 3 release](https://user-images.githubusercontent.com/3064318/52751927-b7759300-2fb6-11e9-9146-cecbe0587aac.png)
