### ISSUE TITLE
Confirm behavior of file-related fields

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#180]
For the file related items, I'm assuming that the valid list is any of the filenames from the files field, but want to confirm this assumption for:

Representative Media
Thumbnail
Rendering

If they don't behave as we want we will take these out of the csv and documentation.

**Comment by val99erie** [comment]
The current behavior is that anything you put in the "Representative Media", "Thumbnail", or "Rendering" columns in the CSV will be ignored by the importer.

I removed those columns from the CSV template and the documentation.

**Comment by mark-dce** [comment]
Great, leaving those out for now makes sense.
