### ISSUE TITLE
Check for valid resource type

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#181]
- [x] Check that any resource type submitted is one of the controlled vocabulary options expected by Hyrax and raise an error if it isn't

**Comment by mark-dce** [comment]
Could we make the test case insensitive so I'm not required to match the exact capitalization of "Map or Cartographic Material"?

I would expect everything in my test file except for row 3 to be valid - especially row 5 & 6. 

```
The CSV file has the following errors:
Invalid Resource Type in row 1: iMaGe
Invalid Resource Type in row 3: 123456
Invalid Resource Type in row 4: othER
Invalid Resource Type in row 5: part of book|~|journal|~|article
Invalid Resource Type in row 6: map or cartographic material
```

I should also be able to import multiple resource types to match the behavior in the User Interface
```
The CSV file has the following errors:
Invalid Resource Type in row 2: Poster|~|Image
Invalid Resource Type in row 3: 123456
Invalid Resource Type in row 5: Part of Book|~|Journal|~|Article
Invalid Resource Type in row 6: Map Or Cartographic Material
```

![181 - multiple resource types](https://user-images.githubusercontent.com/3064318/52673930-b6c1fb80-2ee7-11e9-8d30-2161752b961f.png)

**Comment by mark-dce** [comment]
Moving the case insensitivity & multiple values requirements to ticket #190.
