### ISSUE TITLE
Importer should not allow multiple Rights Statement or Licenses

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#207]
**ISSUE**
The CSV importer currently allows me to supply multiple `Rights Statements` or `Licenses`.  These will import without error and display on the item show page.  When I edit the item, the UI only allows a singe value in these fields and will only save one of the values.

**ACCEPTANCE**
OPTION ONE
- [ ] Report rows with multiple `Rights Statement` or `License` values as warnings
    - [ ] Inform the user that only the first value will be applied
- [ ] If the user chooses to proceed with the import from the warning screen, only import the first value

OPTION TWO
- [ ] Report multiple values in the 'Rights Statement` or `License` as a row-level error and do not allow import of that row.

**Comment by val99erie** [comment]
We might also consider filing a bug against Hyrax.  Both `license` and `rights_statement` are defined in `Hyrax::BasicMetadata` to allow multiple values.  It seems like a mis-match to say that a field is multi-value when you are storing or retrieving data, but then design the UI as though it's a single value.
