### ISSUE TITLE
Ensure Splunk is logging imports on all Tenejo environments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#209]
**ISSUE**
I just ran an import on https://tenejo-stage.curationexperts.com at approximately 2:50pm Central on 2/18/2019 and I don't see anything like a CSV import log.

We'll need this logging configured correctly before we can run reliable ingest baselines.

**ACCEPTANCE**
- [x] Logs have consistent names and locations in each environment
- [x] CSV Imports on tenejo-stage are visible in Splunk
- [x] CSV Imports on tenejo-dev are visible in splunk
- [x] CSV Imports on tenejo-prod (https://tenejo.curationexperts.com) are visible in splunk

**Comment by bess** [comment]
This is set up but splunk is currently reporting this message:
```
Daily indexing volume limit exceeded today. See License Manager for details.
```

I guess we need to pare back what we're logging again? Or else upgrade our plan?

**Comment by bess** [comment]
The logfile you're looking for should be `/opt/tenejo/current/log/darlingtonia_import.log`.
