### ISSUE TITLE
Missing template page for 404 Error

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#242]
[tenejo PROD/production] ActionView::MissingTemplate: Missing template pages/error_404, application/error_404 with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:  * "/opt/tenejo/releases/20190710165427/app/views"  * "/opt/tenejo/shared/bundle/ruby/2.5.0/gems/hydra-role-management-1.0.0/app/views"  * "/opt/tenejo/shared/bundle/ruby/2.5.0/gems/devise-4.6.1/app/views"  * "/opt/tenejo/shared/bundle/ruby/2.5.0/gems/qa-2....

## Backtrace

    line 6 of [PROJECT_ROOT]/app/controllers/pages_controller.rb: error_404
    line 9 of [PROJECT_ROOT]/config/exception_middleware.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/59583/faults/52009944)

**Comment by little9** [comment]
The current solution to avoid these errors works for requests to html pages, but not css, json, xml, rss etc.
