### ISSUE TITLE
All working files should be in project directory

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#302]
**STORY**
The current development configuration requires the creation of a root level folder for data storage: "Make sure your computer has directories /opt/uploads/ and /opt/derivatives that you own".  All data in the development environment should be managed within the project directory

**ACCEPTANCE**
- [ ] The settings should have a safe automatic default for development and test environments
    - [ ] Uploads, cache, and derivatives paths should point to `./tmp` in the development environment
- [ ] The settings should be configurable for production environments where we usually want to point to a persistent volume somewhere else in the directory tree (like `/opt/data`)
- [ ] The system readme should be updated (the instruction can probably be removed since special configuration is no longer required)

**DETAILS**
See the settings at 
https://github.com/curationexperts/tenejo/blob/70becadde935ff963c9372c45c221bf24a067f38/config/initializers/hyrax.rb#L191-L196

**Comment by maxkadel** [comment]
Looks like this is still an issue if you're running outside of docker and don't have UPLOAD_PATH set in your environment.

**Comment by mark-dce** [comment]
Can be resolved by setting directory ENV variables to point to ./tmp/folder in .env.development
