### ISSUE TITLE
Test latest Zizia release with Tenejo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#303]
**ACCEPTANCE**
- [x] Update the application dependencies to point to the newest Zizia release (depends on curationexperts/zizia#95)
If the update passes the test suite, 
- [ ] release a new tenejo version;
otherwise,
- [ ] Write up tickets describing and test failures or other issues that need to be resolved

**Comment by fnibbit** [comment]
https://github.com/curationexperts/tenejo/pull/309

**Comment by maxkadel** [comment]
Have not created a release since the linked PR (last release was on 2/11/2020)

**Comment by fnibbit** [comment]
Also mml sez hm, the zizia gem is somehow adding a migration to the tenejo environment
3:28
pretty sly
3:29
that's why we get that migration error
3:31
it also appears to run after all the tenejo migrations, and has almost as many!
3:33
how do we feel about this?
