### ISSUE TITLE
Update ruby and rails version in test suite 

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#304]
**STORY**
We would like Tenejo to track the [ruby and rails versions supported by Hyrax](https://github.com/samvera/hyrax/blob/master/.circleci/config.yml#L128)

**ACCEPTANCE**
- [x] Update Tenejo to run against the most recent ruby and rails versions supported by Hyrax

**Comment by oraposa** [comment]
working build for ruby 2.7.4 and rails 5.2.6 at [304-update_ruby_and_rails_version_in_test_suite](https://github.com/curationexperts/tenejo/tree/304-update_ruby_and_rails_version_in_test_suite). 

Will look in to Dependabot alerts.

**Comment by oraposa** [comment]
I have passing tests with the rubocop upgrade to 0.85.1. Waiting on CI.

**Comment by oraposa** [comment]
CI has passed. PR created https://github.com/curationexperts/tenejo/pull/404

**Comment by oraposa** [comment]
branch deployed to [tenejo-steve](https://tenejo-steve.curationexperts.com/).

N.B.: Post deployment, I had to manually install bundler 2.2.28, and run `sudo systemctl restart solr`

**Comment by mark-dce** [comment]
I updated `tenejo-cd` so that the deploy-job portion of CI could complete successfully.  Tenejo main is now green.

![image](https://user-images.githubusercontent.com/3064318/135735890-83dc677c-6c4c-419b-9e3f-cfe35bf6bfb5.png)
