### ISSUE TITLE
Deploying Tenejo

### ISSUE THREAD

**Issue by fnibbit** [curationexperts-deprecated/tenejo-v1#307]
Developers can deploy to tenejo-dev, tenejo-stage, tenejo-prod
Acceptance criteria:
Using the documented deploy process and the default branch of tenejo, each environment has had a successful deploy
- [ ] dev
- [ ] stage
- [ ] prod
and each developer has deployed at least once
- [ ] Max
- [ ] Rachel K
- [ ] Bess
- [ ] McClain
- [ ] Mark

**Comment by mark-dce** [comment]
Completed for current tenejo environments
