### ISSUE TITLE
Bug: Collection view behavior

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#310]
Collection View Bug:  

I can toggle between list and gallery views, but once I click masonry I can't go back to list and gallery.

Steps to reproduce:
Go to Playing Cards collection. Toggle between list and gallery views (by clicking the icons) -- Then click icon for masonry view. Then attempt to click back to list or gallery views.

(A similar issue was reported and "closed" in Hyrax github. Not sure what version that work was in.)

This was found on this version:
Tenejo v1.12.0; Updated 11 February 2020
Hyrax v2.5.1

**Comment by mark-dce** [comment]
We'll retest in Hyrax 3.x
