### ISSUE TITLE
SPIKE: Evaluate bulk upload options

### ISSUE THREAD

**Issue by mlooney** [curationexperts-deprecated/tenejo-v1#344]
Evaluate options for bulk upload:

* 3rd party service (wetransfer.com, massive.io, others?) (also one drive, google drive, etc.)
* ~open source options: (ActiveStorage bulk upload)~
* scp/sftp/filezilla/browser plugin (chrome sftp plugin etc)

Acceptance: write up pros/cons of each

**Comment by maxkadel** [comment]
Mark's Q: From a user standpoint, how will the bulk upload tool integrate into the application? 

Per McClain - for clients without an IT staff the third party services seem nicest, but are 3rd party and cost money. Some connect with AWS S3.

**Comment by maxkadel** [comment]
https://docs.google.com/document/d/11FiD8_e3U6XkcTd8-FktgSNqWArgYlNjAmxaiixeHBo/edit?usp=sharing

**Comment by maxkadel** [comment]
Suggestion: Use SCP until more of the user design is done, before choosing client-facing service.
