### ISSUE TITLE
Make the CSV Template

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#41]
**ACCEPTANCE**
- [x] Choose the template to use to start import 
- [x] Check a sample into tenejo version control and link it to this ticket

NOTE: Darlingtonia + a file column is a good starting point.  & Then figure out if we want to drop any column headers

**Comment by mark-dce** [comment]
**ACCEPTANCE**
- [ ] Choose the template to use to start import 

NOTE: Darlingtonia + a file column is a good starting point.  & Then figure out if we want to drop any column headers

**Comment by mark-dce** [comment]
I'm looking at the [Darlingtonia CSV](https://github.com/curationexperts/darlingtonia/blob/master/spec/fixtures/hyrax/example.csv) and I'm thinking that in addition to a **file_attachments** column, we need additional columns which specify:
* **visibility**: public, restricted to login, private (or we need to handle this like collections and prompt at the beginning of the import, but I can see cases where you'd have mixed visibility within a collection)
* **representative_media** - if there are multiple files attached, one needs to be marked as the primary 
* **thumbnail** - if there are multiple files and a different file is used for thumbnail display in search results (like a video still) than is used in the primary show page (like the full video)
* **rendering** - which file(s) are available for download in Universal Viewer

In terms of ensuring our solution design is complete we should take these into account.  However, we can make default assumptions about these in their absence or for the purposes of an initial MVP: e.g. private visibility if not specified otherwise,  first file listed is representative, etc.

**Comment by val99erie** [comment]
You can download the template file here:
https://tenejo-cd.curationexperts.com/import_manifest.csv

**Comment by mark-dce** [comment]
Looks good overall.  We'll add some documentation as a separate ticket.
