### ISSUE TITLE
Make the CSV Template Downloadable

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#42]
- [x] Add a link to left dashboard bar "Download CSV Template" that links to the CSV from #41
- [x] The template should have correct headers, but no sample data*
- [x] Wrap this in a feature flipper (so we can turn it off on prod)

`* We'll provide some sample completed example CSVs on a support wiki later.

**Comment by val99erie** [comment]
Info for developer:
You can probably just serve the file from the public folder:
https://localhost:3000/import_manifest.csv

**Comment by mark-dce** [comment]
I like that idea.  I was just thinking it might be good to check in some kind of version controlled documentation that documents the field usages and it would be great to have the two files checked in somewhere that it was obvious they were related.  I.E. could we have *import_manifest.csv* and *import_manifest.md* both checked into and served from the public folder.
