### ISSUE TITLE
Report out on AWS Offerings

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#47]
**REQUEST**
As a manager, I would like the team to have a basic understanding of available AWS technologies that might be used as part of a hosted repository solution.

**ACCEPTANCE**
- [ ]  Provide a 15-25 minute overview of
    - [ ] EBS
    - [ ] S3
    - [ ] Glacier
    - [ ] AWS Import/Export Disk
    - [ ] Snowball
    - [ ] Snowmobile

**Comment by little9** [comment]
https://github.com/curationexperts/in-house/wiki/AWS-Storage-Comparison
