### ISSUE TITLE
Report out on Box CLI and API

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#48]
**REQUEST**
As a manager, I would like the team to better understand the way we might use box's API and CLI to support potential hosting solutions.

**ACCEPTANCE**
- [x] a 15-25 minute overview of
   - [x] Box API
   - [x] Box CLI

**Comment by bess** [comment]
Slides here: https://docs.google.com/presentation/d/1lOahOSvU60lu85wN5iuT7y1ycTcwPusZAOUG_o1UFLg/edit?usp=sharing

This presentation will be very short.
