### ISSUE TITLE
SPIKE: Virus Checking performance

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#49]
**EXPERIMENT**
When running virus checking on enough files to get meaningful timings
- [x] Loading ClamAV once and running it on all files in the folder
- [x] Loading ClamAV multiple times, once for each individual file (like the actor stack would)

- [x] How many files do we need in our sample set

**Comment by bess** [comment]
Sample set is 16 tiff files from UCLA's Connell collection, plus one virus testing file (to ensure it's actually checking for viruses).

Running for all files in a folder:
```
time clamscan .
real    0m16.226s
```

Running the same directory, each file individually: 
```
time for i in `find .`; do clamscan $i; done
real    6m1.177s
```

So, 16.226 seconds for the batch, vs 6 minutes and 1.177 seconds when we launch a separate clamav process for each file. We have a clear winner.

**Comment by mark-dce** [comment]
Super cool - so doing Virus scan outside the actor stack seems like a really good idea!  Let's figure out what that might look like.
