### ISSUE TITLE
SPIKE: derivative performance

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#50]
**EXPERIMENT**
When making derivatives on enough files to get meaningful timings
- [x] Loading Imagemagick once and running it on all files in the folder
- [x] Loading Imagemagick multiple times, once for each individual file (like the actor stack would)

- [x] How many files do we need in our sample set

**Comment by little9** [comment]
**Loading Imagemagick once and running it on all files in the folder:**

Command:
`mogrify -format jpg *.tiff`

Result:
```
1.21user 0.23system 0:01.48elapsed 97%CPU (0avgtext+0avgdata 105980maxresident)k
0inputs+37360outputs (0major+221242minor)pagefaults 0swaps
```
**Loading Imagemagick multiple times, once for each individual file (like the actor stack would)**

Script:

```sh
#!/bin/bash
mogrify -format jpg IMG_0036.tiff
mogrify -format jpg IMG_0038.tiff
mogrify -format jpg IMG_0039.tiff
mogrify -format jpg IMG_0040.tiff
mogrify -format jpg IMG_0041.tiff
mogrify -format jpg IMG_0042.tiff
mogrify -format jpg IMG_0043.tiff
mogrify -format jpg IMG_0044.tiff
mogrify -format jpg IMG_0045.tiff

```

Result:

```
1.24user 0.25system 0:01.55elapsed 97%CPU (0avgtext+0avgdata 106064maxresident)k
0inputs+37360outputs (0major+226071minor)pagefaults 0swaps
```

**Comment by mark-dce** [comment]
Am I reading that correctly if I interpret it to mean it takes 0.07s longer to run file-by-file?  And then is it reasonable to extrapolate that it takes 0.07s/9 or ~0.01s per file additional overhead to do file-by-file?  

If all that reasoning is correct, then it seems like processing 5,000 files one-by-one would only add about a minute to the overall processing time.  I'm not sure I trust all that reasoning though, and I'm wondering how hard it would be to try this on a much larger sample size?  I think the whole LADNN collection is on one of the DCE california dev servers.  Could we turn one of those servers back on and run the same test against a big set of file?

**Comment by little9** [comment]
You're reading it right. 

I couldn't find the LADNN files so I just ran this test with 1000 21 MB tiffs:

All at once:
```
178.05user 31.73system 4:30.46elapsed 77%CPU (0avgtext+0avgdata 140428maxresident)k
41536576inputs+6086080outputs (1066major+24340579minor)pagefaults 0swaps
```
One at a time:
```
182.77user 35.07system 4:36.97elapsed 78%CPU (0avgtext+0avgdata 105784maxresident)k
41478680inputs+6080000outputs (1134major+25308891minor)pagefaults 0swaps
```

**Comment by mark-dce** [comment]
It sounds like the last test we want to do is to figure out the overhead of shelling out from a rails application.  So, could we do one final round on the 1000 items that calls `mogrify -format jpg *.tiff` vs. something like  files.each { |f| `mortify  - format jpg #{f}` }

NOTE: my rails & ruby syntax above is horrible and invalid...

**Comment by little9** [comment]
@mark-dce It looks like the ruby version (using MiniMagick like hydra-derivatives) comes out ahead:

```ruby
require 'mini_magick'

tiffs = Dir.glob('*.tiff')
tiffs.each do |tiff|
  image = MiniMagick::Image.open(tiff)
  image.format 'jpg'
  image.write tiff + '.jpg'
end
```

```
182.31user 46.52system 4:20.44elapsed 87%CPU (0avgtext+0avgdata 105688maxresident)k
41528656inputs+53693640outputs (11major+25459695minor)pagefaults 0swaps
```

**Comment by mark-dce** [comment]
That's awesome and totally not what I would have expected.  Nice job!
