### ISSUE TITLE
SPIKE: Bulk File Upload Options

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#52]
Using the examples we looked at Tuesday morning, pick *at least two* and *no more than eight* options and walk through them to capture screenshots, compare functionality and report back.

Potential comparison criteria probably include 

* User experience, clarity, simplicity, number of steps
* How much of the solution can be automated
* Difficulty to implement
* Difficulty to support / debug
* Reusability in other client contexts
* Estimated Annual Cost
* Others as appropriate 

Links to all the drawings 
Initial Idea https://docs.google.com/drawings/d/1GuoKXnBvEvp27N04ATW9EBg597atcGanSGUfD2R3zDI/edit 
DCE Owned Box https://docs.google.com/drawings/d/1INJDZRw_IHocNE6IFwx4VKMh0LX9Du822qLhz1vUFlo/edit 
Client Owned Box https://docs.google.com/drawings/d/1Eimqmtvnc7M2lhm3e7cmmmB2jvmF31pQdT4D2LGs4xM/edit 
DCE Owned S3 https://docs.google.com/drawings/d/1VpRDSoKftJtV9Qxubf72ocSyyWtb2iafXDz0w1XXiHo/edit 
SCP to server https://docs.google.com/drawings/d/1K6nfTporH6AIz2ogjqqzwxNtpa92z7VC_ytMvwRNfEY/edit 
Use Hyrax Upload Multiple works - no sketch yet...
Side Ideas
Use Actor Stack https://docs.google.com/drawings/d/19Ji83G8qAxq87vJ1gu1Am6qo0bhq4hz9EgeyN-Z08gc/edit 
Process in batches https://docs.google.com/drawings/d/1Jdx87BiqKBl3YesvacJRw1_-VH9ceTzp8zJjsVYKJ3Y/edit

**Comment by bess** [comment]
Notes here: https://docs.google.com/document/d/1ux7x4lzrUmSROn9Akh7tFv37uScuPT3BIgMsljtJT3w/edit?usp=sharing

**Comment by bess** [comment]
I researched six options and got working prototypes going for two of these. My favorite is SFTP + FileZilla.

![filezilla_upload.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46ee9d9626988aa583e88056b451ff952d046b313916ac217586f76ae5002e035e564aa547595f4daafedb2ca6b63d238a0e0dbf836b4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ec3a22e4838a46361c031d9bb2.png)

**Comment by mark-dce** [comment]
Looks awesome.
