### ISSUE TITLE
Initial Documentation of CSV fields

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#62]
**ACCEPTANCE**
- [x] For each field in https://tenejo-cd.curationexperts.com/import_manifest.csv, provide a sentence or two about what should be in the field.  Give examples where helpful.
- [x] Indicate which fields can be multi-valued.
- [x] Document how to add multiple values to multi-valued fields.
- [x] Check documentation into Github.
- [x] Display the documentation in the application

**Comment by mark-dce** [comment]
NOTE: We might want *import_manifest.csv* and *import_manifest.md* both checked into and served from the public folder. See #42

**Comment by val99erie** [comment]
This might be helpful:
http://samvera.github.io/metadata_application_profile.html

**Comment by little9** [comment]
| CSV Header  | title    | files    | representative_media | thumbnail | rendering | depositor | date_uploaded    | date_modified | label                                             | relative_path                                | import_url                                | resource_type | creator      | contributor      | description    | keyword       | license   | rights_statement | publisher      | date_created   | subject      | language      | identifier     | based_near      | related_url   | bibliographic_citation   | source    | visibility | 
|-------------|----------|----------|----------------------|-----------|-----------|-----------|------------------|---------------|---------------------------------------------------|----------------------------------------------|-------------------------------------------|---------------|--------------|------------------|----------------|---------------|-----------|------------------|----------------|----------------|--------------|---------------|----------------|-----------------|---------------|--------------------------|-----------|------------| 
| Predicate   | DC.title |          |                      |           |           |           | DC.dateSubmitted |               | ActiveFedora::RDF::Fcrepo::Model.downloadFilename | http://scholarsphere.psu.edu/ns#relativePath | http://scholarsphere.psu.edu/ns#importUrl | DC.type       | DC11.creator | DC11.contributor | DC.description | DC11.relation | DC.rights | EDM.rights       | DC11.publisher | DC.created     | DC11.subject | DC11.language | DC.indentifier | FOAF.based_near | RDFS.seeAlso  | DC.bibliographicCitation | DC.source |            | 
| Cardinality | multiple | multiple | singular             | singular  |           | singular  | singular         | singular      | singular                                          | singular                                     | singular                                  | multiple      | multiple     | multiple         | multiple       | multiple      | multiple  | singular         | multiple       | multiple       | multiple     | multiple      | multiple       | multiple        | multiple      | multiple                 | multiple  |            | 
| Data Type   | string   | string   |                      |           |           |           |                  |               |                                                   |                                              |                                           | string        | string       | string           | string         | string        | uri       | uri              | string         | date or string | string       | string        | string         | uri             | string or uri | string                   | string    |            | 
| Optionality | required | optional | optional             | optional  | optional  | required  | required         | required      | optional                                          | optional                                     | optional                                  | optional      | required     | optional         | optional       | optional      | optional  | required         | optional       | optional       | optional     | optional      | optional       | optional        | optional      | optional                 | optional  | optional   |

**Comment by little9** [comment]
@mark-dce is something like that OK to start with?

**Comment by mark-dce** [comment]
That seems way more technical than end-user focused.  Why don't you work with @RachelDCE and see what kind of information she thinks she's need to fill out the CSV correctly.  

To be honest, I was looking for something more like:

CSV TEMPLATE INSTRUCTIONS
=======================
Each row in the CSV corresponds to a work that will be created when the importer is run.  

**title** [REQUIRED] Each work requires a unique title.  Titles can be any length, but we recommend keeping them under 250 characters so the can be easily read in search results.  Titles may include non-english characters in UTF8 encoding.

**files** [REQUIRED] List each file that should be imported and attached to the work.  Each work must have at least one file attached.  Files can be of any type: the system will detect images, documents, video, and audio and display corresponding thumbnails and viewers; other types of files will be indicated by a generic file icon and provide download options if there is no specific viewer/player available.  To attach multiple files to a work, separate the file names with `|~|`, e.g. `image1.jpg|~|image2.jpg|~|research-paper.doc`.

**representative** [optional] Identifies which file should be used as the representative for the work on the primary page for the work.  If no file is specified, the first file listed in `files` is used.

etc.

**Comment by mark-dce** [comment]
@jamie - I'm getting a "We're sorry but something went wrong" error at https://tenejo-cd.curationexperts.com/importer_documentation/guide

It looks like 9c9731bffbeb639a634f6e1f7f46afff3ffaf7f7 is the commit that's deployed

**Comment by jamie** [comment]
^ cc @little9

**Comment by mark-dce** [comment]
@little9 - ignore that looks like that's not the right commit - I'll check back in an hour and see if the code is deployed

**Comment by mark-dce** [comment]
yay!!!

![62 - initial documentation](https://user-images.githubusercontent.com/3064318/52299051-1ea59e80-294a-11e9-9dcb-55290133d707.png)
