### ISSUE TITLE
Use Darlingtonia? Something else?

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#70]
**STORY** 
As a product owner I would like the team to make a recommendation regarding using Darlingtonia going forward or writing alternative import code so that we can continue moving forward with the self-service importer.

**Questions to ask**
* Does Darlingtonia help meet our design goal better than new code?
* How well does Darlingtonia meet each of our design criteria?
* Does Darlingtonia prematurely generalize requirements that are not concrete in the problem? (See Sandi Metz - [The Wrong Abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction) )
* How easily does Darlingtonia support the logging requirements in #72 *Importer error reporting*

Depends on #74

**Comment by mark-dce** [comment]
Based on Bess's work on #70 we think Darlingtonia is a good starting place. So we'll go from here.
