### ISSUE TITLE
Content upload via SFTP

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#73]

**Comment by RachelDCE** [comment]
**STORY**
As a customer I can use a SFTP client to upload the files I want to import.

**ACCEPTANCE**
- [x] A user can use Filezilla to upload content to a Tenejo server.

**Comment by bess** [comment]
PR Here: https://github.com/curationexperts/dce-cm/pull/30

This is in effect on all tenejo servers now. Login details are on the wiki, here: https://github.com/curationexperts/in-house/wiki/Tenejo

**Comment by mark-dce** [comment]
FYI - It looks like I need to manually type the password in and explicitly set the port to 22 when using filezilla pro.
