### ISSUE TITLE
Try to build an importer using Darlingtonia

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#74]
Write a Darlingtonia importer for Tenejo 

Refer to story #70 to decide if it meets our criteria.

**Comment by bess** [comment]
* Improved documentation here: https://curationexperts.github.io/darlingtonia/
* Darlingtonia 2.0 (to be released soon) has been updated to use Hyrax defaults, which will make it much easier to add an importer in the future. 
* Tenejo has work in progress to use the latest Darlingtonia patterns and has a command line importer built (but not yet merged). 
* Work to complete the importer will be covered in future tickets.
