### ISSUE TITLE
Show record count on preview screen

### ISSUE THREAD

**Issue by val99erie** [curationexperts-deprecated/tenejo-v1#83]
Acceptance Criteria

- [ ] On the [page to start a new CSV import](https://tenejo-cd.curationexperts.com/csv_imports/new), when I fill in the form and click 'Preview Import', the preview screen should display the number of records that are in the CSV file.

**Comment by val99erie** [comment]
Some info that might help whoever writes this code:

The view page for the preview screen:
https://github.com/curationexperts/tenejo/blob/master/app/views/csv_imports/preview.html.erb#L13

The CSV uploader has a validator that already knows the number of records:
https://github.com/curationexperts/tenejo/blob/master/app/uploaders/csv_manifest_validator.rb#L36-L39

You might be able to follow the example of how the `errors` and `warnings` that come from the validator get displayed on the preview page:
https://github.com/curationexperts/tenejo/blob/master/app/uploaders/csv_manifest_uploader.rb#L27-L29

**Comment by mark-dce** [comment]
Looks good

<img width="758" alt="83 - record cound" src="https://user-images.githubusercontent.com/3064318/52013093-d1d14c00-24a1-11e9-89d1-99ffab891009.png">
