### ISSUE TITLE
Query solr instead of fedora for collection selector

### ISSUE THREAD

**Issue by val99erie** [curationexperts-deprecated/tenejo-v1#84]
**Background Info:**

In the form to start a new CSV import, the selector drop-down calls `Collection.all` to generate the collection IDs and titles for the select options:
https://github.com/curationexperts/tenejo/blob/master/app/views/csv_imports/_collection_selection.html.erb#L3

This causes all the collection records to be loaded from fedora, which is probably fine for the MVP release and fine for a small number of collections, but we would have better performance if we used a solr query instead.

**Acceptance Criteria:**

- [x] Use a solr query to fetch the ids and titles instead of `Collection.all`.

**Comment by mark-dce** [comment]
It's hard for me to tell from a user's perspective if this one is working or not, so I'm going to go by the PR and close this ticket.
