### ISSUE TITLE
Display collection title instead of ID

### ISSUE THREAD

**Issue by val99erie** [curationexperts-deprecated/tenejo-v1#85]
Acceptance Criteria:

- [x] On the [page to start a new CSV import](https://tenejo-cd.curationexperts.com/csv_imports/new), when I fill in the form and click 'Preview Import', the preview page should display the title of my selected collection (instead of the collection ID).

- [x] Then, when I click the 'Start Import' button, the show page for that import should also display the collection's title, not it's ID.

**Comment by mark-dce** [comment]
Hey - it looks like the collection name is now being shown in brackets and quotes on the "Start CSV Import" page.  @RachelDCE and I don't remember that from last time we looked at the screen.

Can you either fix that or write it up as a new ticket (i.e. it feels like a regression introduced in this ticket based on what we remember seeing, but if we're remembering wrong, it can just be a new ticket)

<img width="367" alt="85 - collection name in quotes" src="https://user-images.githubusercontent.com/3064318/51941315-eb0ec580-23d9-11e9-9c1b-7ad8ae7ad76c.png">

**Comment by mark-dce** [comment]
Thanks for fixing the dropdown.  I can see the collection name on the summary page as expected too:

<img width="576" alt="85 - collection name displays as expected" src="https://user-images.githubusercontent.com/3064318/51993188-f0b8e980-2473-11e9-90f5-1af23378486b.png">
