### ISSUE TITLE
Location lookup doesn't work

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#89]
**ISSUE**
When I enter text in the location field for a new object, I get the message "No Matches Found" regardless of what text I enter - even something like "Los Angeles" says no matches.

**ACCEPTANCE**
- [ ] I can search for and enter a specific location and save it with my object.

**Comment by little9** [comment]
@mark-dce For this to work we need to set the GeoNames username. Someone will need to 
register at GeoNames: http://www.geonames.org/login (it requires an email)

**Comment by mark-dce** [comment]
@little9 & @bess I think we have it running under a DCE account on nurax (and I though we had it configured for demo.curationexperts.com at some point in the past).  Can you check the nurax config and see if we can use the same credentials?  If not, feel free to sign up using either `contact@curationexperts.com` or `systems@curationexperts.com` - I think Bess should have access to both those mailboxes and I definitely do if we need to confirm sign up or anything similar.

**Comment by mark-dce** [comment]
Thank you!

Edit form
---------
![89 - locaion lookup on edit form](https://user-images.githubusercontent.com/3064318/52221629-30fadc00-2867-11e9-8768-75ced5a457d4.png)

Show view
-----------
![89 - locaion lookup on show view](https://user-images.githubusercontent.com/3064318/52221630-31937280-2867-11e9-8e38-4b4ccedfff48.png)
