### ISSUE TITLE
Configure basic Hyrax virus checking

### ISSUE THREAD

**Issue by mark-dce** [curationexperts-deprecated/tenejo-v1#99]
**ACCEPTANCE**
- [x] The system does not attach infected files to works
- [x] Write up how to configure Hyrax to do virus checking

**Comment by little9** [comment]
https://github.com/curationexperts/in-house/wiki/Adding-Virus-Checking-to-Hyrax

**Comment by mark-dce** [comment]
Looks good see #100 for screenshot
